// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface D1Database {
  prepare: (query: string) => D1PreparedStatement;
}

interface D1PreparedStatement {
  bind: (...values: any[]) => D1PreparedStatement;
  all: () => Promise<{ results: any[] }>;
  run: () => Promise<{ success: boolean }>;
}

interface CloudflareEnv {
  DB: D1Database;
  JWT_SECRET?: string;
  NODE_ENV: 'development' | 'production' | 'test';
}

declare global {
  namespace NodeJS {
    interface ProcessEnv extends CloudflareEnv {}
  }
}
